// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIhsnRh8fdqkhb0MGWD6tAvIPAWil_nHc',
    appId: '1:903842582798:web:56fb50af51b6eb2961075f',
    messagingSenderId: '903842582798',
    projectId: 'electra-hardware',
    authDomain: 'electra-hardware.firebaseapp.com',
    storageBucket: 'electra-hardware.firebasestorage.app',
    measurementId: 'G-0G51V8HGYQ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2xInBw6Pw1pUFF_Aqi_2hnui45L6TFSg',
    appId: '1:903842582798:ios:b5a680276571cdcc61075f',
    messagingSenderId: '903842582798',
    projectId: 'electra-hardware',
    storageBucket: 'electra-hardware.firebasestorage.app',
    iosBundleId: 'com.electrahardware.electraHardware',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2xInBw6Pw1pUFF_Aqi_2hnui45L6TFSg',
    appId: '1:903842582798:ios:b5a680276571cdcc61075f',
    messagingSenderId: '903842582798',
    projectId: 'electra-hardware',
    storageBucket: 'electra-hardware.firebasestorage.app',
    iosBundleId: 'com.electrahardware.electraHardware',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIhsnRh8fdqkhb0MGWD6tAvIPAWil_nHc',
    appId: '1:903842582798:web:11a7cf50760a5d3761075f',
    messagingSenderId: '903842582798',
    projectId: 'electra-hardware',
    authDomain: 'electra-hardware.firebaseapp.com',
    storageBucket: 'electra-hardware.firebasestorage.app',
    measurementId: 'G-VPVQQH34M3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl6Gn1LsGetlLi2-aQaVxWPQVk6feNXyM',
    appId: '1:903842582798:android:43b2cfe0df28055261075f',
    messagingSenderId: '903842582798',
    projectId: 'electra-hardware',
    storageBucket: 'electra-hardware.firebasestorage.app',
  );
}
